### ISSUE TITLE
Improve this .fgd

### ISSUE THREAD

**Issue by Bouh** [kidfearless/csgo_extended.fgd#1]
Hello

I've found another version of csgo_extended.fgd
Maybe it can be merge with your version ?
https://pastebin.com/raw/JUxuYWFa

[.fgd with vmt](https://cdn.discordapp.com/attachments/246325301817114624/475778313688842250/enhanced_fgd.zip)

**Comment by RyamosThomas** [comment]
From what I saw all that one does is add fancy icons to some entities. It doesn't really extend functionality.

**Comment by Revoker7x** [comment]
I wouldn't mind having Zool's icons in the FGD, maybe we can contact him and combine the projects or add him as a contributor

**Comment by Bouh** [comment]
Maybe, I know zool have a discord server you can ask him on it. You can
found server on YouTube in description under videos

**Comment by Revoker7x** [comment]
Just wanted to add that Zool gave the ok

https://i.imgur.com/KQMDDt5.jpg
